M48
; DRILL file {KiCad 9.0.1} date 2025-06-15T18:00:24+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-15T18:00:24+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X45.75Y-35.05
X45.75Y-104.9
X122.15Y-35.05
X122.15Y-104.9
M30
