M48
; DRILL file {KiCad 9.0.1} date 2025-06-25T22:08:25+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-25T22:08:25+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X45.75Y-34.9
X45.75Y-104.9
X122.75Y-34.9
X122.75Y-104.9
M30
